name: CI Pipeline

on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Use GitHub Token
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: |
        echo "Using GitHub Token"
        curl -H "Authorization: token $TOKEN" https://api.github.com
      
    - name: Install Case
      run: |
        cd Phase\ 1/src
        ./run install
        
    - name: Test Case
      run: |
        cd Phase\ 1/src
        ./run test
        
    - name: URL Case
      run: |
        cd Phase\ 1/src
        ./run ../reference/SampleUrlFile.txt
