name: Testing run script options

on:
  pull_request:
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3
      
    - name: install_case
      run: |
        cd ECE46100-Team
        ./run install
        
    - name: test_case
      run: | 
        cd ECE46100-Team
        ./run test
        
    - name: url_case
      run: |
        cd ECE46100-Team
        ./run Phase\ 1/reference/SampleUrlFile.txt 
