name: CI Pipeline
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.TOKEN}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Environment Variables
        run: |
          echo "LOG_FILE=logs/app.log" >> $GITHUB_ENV
          echo "LOG_LEVEL=2" >> $GITHUB_ENV

      - name: Install Dependencies
        run: |
          npm install

      - name: Install Case
        run: |
          cd Phase\ 1/src
          ./run install

      - name: Test Case
        run: |
          cd Phase\ 1/src
          ./run test

      - name: URL Case
        run: |
          cd Phase\ 1/src
          ./run ../reference/SampleUrlFile.txt

      - name: Run ESLint
        run: |
          npm run eslint .

      - name: Run Prettier Check
        run: |
          npm run prettier --check .

      - name: Run Prettier Format
        run: |
          npm run prettier --write .
