name: Testing run script options

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install_case
      run: ./run install
    - name: test_case
      run: ./run test
    - name: url_case
      run: ./run Phase\ 1/reference/SampleUrlFile.txt 
