name: Testing run script options

on: [push, pull_request]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: Set Environment Variables
      run: |
        echo "LOG_FILE=logs/app.log" >> $GITHUB_ENV
        echo "LOG_LEVEL=1" >> $GITHUB_ENV
        echo "GITHUB_TOKEN=placeholder" >> $GITHUB_ENV
      
    - name: Install Case
      run: |
        cd Phase\ 1/src
        ./run install
        
    - name: Test Case
      run: |
        cd Phase\ 1/src
        ./run test
        
    - name: URL Case
      run: |
        cd Phase\ 1/src
        ./run ../reference/SampleUrlFile.txt
